name: OreGenerator
version: 2.0
main: dev.incognitojam.oregenerator.OreGenerator
api-version: '1.20'
authors: [ incognitojam ]
description: Better cobblestone generators
website: https://github.com/incognitojam/ore-generator
